server {
    listen 9090;
    server_name site1.test;
    host 127.0.0.1;
    root www;
    index index.html;
    client_max_body_size 3000000;

    error_page 404 errors/404.html;

    location / {
        allow_methods get post delete;
        root www;
        index index.html;
    }

    cgi_conf .py /usr/bin/python3;
}

server {
    listen 9092;
    server_name site2.test;
    host 127.0.0.1;
    root www-b;
    index index.html;
    client_max_body_size 3000000;

    location / {
        allow_methods get post delete;
        root www-b;
        index index.html;
    }
}

server {
    listen 9091;
    server_name site3.test;
    host 127.0.0.1;
    root www-c;
    index index.html;
    client_max_body_size 3000000;

    location / {
        allow_methods get post delete;
        root www-c;
        index index.html;
    }
}
