#!/usr/bin/python3
import os
import sys

meta_vars = [
    "REQUEST_METHOD", "SCRIPT_NAME", "SCRIPT_FILENAME", "PATH_INFO",
    "QUERY_STRING", "CONTENT_TYPE", "CONTENT_LENGTH",
    "SERVER_NAME", "SERVER_PORT", "SERVER_PROTOCOL", "GATEWAY_INTERFACE",
]

body_bytes = b""
content_length = int(os.environ.get("CONTENT_LENGTH", "0") or "0")
if content_length > 0:
    body_bytes = sys.stdin.buffer.read(content_length)

rows = ""
for key in meta_vars:
    rows += "<tr><td>" + key + "</td><td>" + os.environ.get(key, "<i>(not set)</i>") + "</td></tr>\n"
for key in sorted(k for k in os.environ if k.startswith("HTTP_")):
    rows += "<tr><td>" + key + "</td><td>" + os.environ[key] + "</td></tr>\n"

body_row = ""
if body_bytes:
    body_row = "<tr><td>request body</td><td><code>" + body_bytes.decode(errors="replace") + "</code></td></tr>\n"

html = """<!DOCTYPE html>
<html>
<head>
<title>hello.py -- CGI is alive</title>
<style>
  body { font-family: monospace; background: #0f1115; color: #d7dde3; padding: 2rem; }
  h1 { color: #7ee787; }
  table { border-collapse: collapse; width: 100%%; max-width: 800px; }
  td { border: 1px solid #333; padding: 6px 10px; }
  td:first-child { color: #79c0ff; white-space: nowrap; }
</style>
</head>
<body>
<h1>Hello from CGI!</h1>
<p>This entire page was generated by a Python process your webserv forked, execve'd,
and piped data to/from through your single poll() loop -- not served from a file.</p>
<table>
%s%s</table>
</body>
</html>
""" % (rows, body_row)

body = html.encode()
sys.stdout.buffer.write(b"Content-Type: text/html\r\n")
sys.stdout.buffer.write(("Content-Length: " + str(len(body)) + "\r\n").encode())
sys.stdout.buffer.write(b"\r\n")
sys.stdout.buffer.write(body)
